FROM python:3.10

WORKDIR /app

COPY requirements.development.backend.txt ./
RUN pip install -r requirements.development.backend.txt

COPY . .

EXPOSE 8000

HEALTHCHECK --interval=5s --timeout=1s --retries=5 CMD curl -f http://localhost:8000/api/ || exit 1

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
