# Generated by Django 5.1.1 on 2024-09-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('port_number', models.IntegerField()),
                ('proxy_type', models.CharField(choices=[('S4', 'socks4'), ('S5', 'socks5'), ('HP', 'HTTP'), ('HS', 'HTTPS')], max_length=2)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('proto', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=25)),
                ('reason', models.CharField(max_length=25)),
                ('ttl', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='internet.host')),
                ('proxy_endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internet.proxy')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='proxy_endpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='internet.proxy'),
        ),
    ]
