# Generated by Django 5.1.1 on 2024-09-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
