# Generated by Django 5.1.1 on 2024-09-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='active',
            new_name='enabled',
        ),
    ]
