# Generated by Django 5.1.1 on 2024-09-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_rename_active_proxy_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='proxy_endpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.proxy'),
        ),
        migrations.AlterField(
            model_name='port',
            name='proxy_endpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.proxy'),
        ),
    ]
