# Generated by Django 5.1.1 on 2024-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_alter_host_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socksproxy',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
