# Generated by Django 5.1.1 on 2024-09-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_alter_host_proxy_endpoint_alter_port_proxy_endpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='number',
            new_name='port_number',
        ),
    ]
