# Generated by Django 5.1.1 on 2024-09-26 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_rename_number_port_port_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='proxy_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.proxy'),
        ),
        migrations.AlterField(
            model_name='port',
            name='proxy_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.proxy'),
        ),
    ]
