# Generated by Django 5.1.1 on 2024-09-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_alter_host_proxy_endpoint_alter_port_proxy_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='proxy_endpoint',
        ),
    ]
