# Generated by Django 5.1.1 on 2024-09-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0010_rename_list_word_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lists',
            field=models.ManyToManyField(related_name='words', to='internet.wordlist'),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
