# Generated by Django 5.1.1 on 2024-09-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0011_alter_word_lists_alter_word_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
