# Generated by Django 5.1.1 on 2024-09-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0013_alter_port_ttl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='proxy_endpoint',
        ),
    ]
