# Generated by Django 5.1.1 on 2024-09-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0014_remove_host_proxy_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.Field(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_names', to='internet.host')),
            ],
        ),
    ]
