# Generated by Django 5.1.1 on 2024-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0015_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
