# Generated by Django 5.1.1 on 2024-09-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0016_dnsrelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrelay',
            name='port',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dns_relay', to='internet.port'),
            preserve_default=False,
        ),
    ]
